linters-settings:
linters:
  enable:
    - bodyclose
    # a lot of false positives
    # - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    # function is too long
    # - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    # * is a global variable
    # - gochecknoglobals
    - gocognit
    - godox
    - maligned
    - prealloc
    # expression shouldn't be cuddled
    # - wsl
    # magic numbers
    # - gomnd
